few_shots = [
     {'Question' : "What is the total price for white nike tshirt with XL size",
      'SQLQuery' : "SELECT Sum(price*stock_quantity) FROM t_shirts WHERE color = 'White' AND brand = 'Nike' AND size = 'XL'",
      'SQLResult': "Result of the SQL query",
      'Answer' : qns6},
     {'Question' : "How much is total price of the inventory for all small size t-shirts?",
      'SQLQuery' : "SELECT SUM(price*stock_quantity) FROM t_shirts WHERE size = 'S'",
      'SQLResult': "Result of the SQL query",
      'Answer' : qns8},
     {'Question' : "What will be net revenue sales for tshirt considering stock quantity as per piece price after applying discount. Sell only the adidas tshirt that have discount",
      'SQLQuery' : "Select sum((t.price * t.stock_quantity)-(t.price * t.stock_quantity * (d.pct_discount/100))) as net_rev_sl FROM t_shirts as t INNER JOIN discounts as d ON t.t_shirt_id = d.t_shirt_id WHERE t.brand = 'Adidas'",
      'SQLResult': "Result of the SQL query",
      'Answer' : qns21},
     {'Question' : "What will be net revenue sales for tshirt considering stock quantity as per piece price after applying discount. Sell all the tshirt that have discounts",
      'SQLQuery' : "select sum((t.price * t.stock_quantity)-(t.price * t.stock_quantity * (d.pct_discount/100))) as net_rev_sl FROM t_shirts as t INNER JOIN discounts as d ON t.t_shirt_id = d.t_shirt_id",
      'SQLResult': "Result of the SQL query",
      'Answer' : qns22},
     {'Question' : "How many red color adidas tshirt are available",
      'SQLQuery' : "select sum(stock_quantity) from t_shirts where color = 'Red' and brand ='Adidas'",
      'SQLResult': "Result of the SQL query",
      'Answer' : qns23},
     {'Question' : "If we sell all adidas tshirt what will be my revenue, consider stock quantity as per piece price and apply discount that have and others not",
      'SQLQuery' : "select (select sum((t.price * t.stock_quantity)) as net_rev_sl from t_shirts as t left join discounts d on d.t_shirt_id = t.t_shirt_id WHERE t.brand = 'Adidas' and d.t_shirt_id is null)+(select sum((t.price * t.stock_quantity)-(t.price * t.stock_quantity * (d.pct_discount/100))) as net_rev_sl FROM t_shirts as t INNER JOIN discounts as d ON t.t_shirt_id = d.t_shirt_id WHERE t.brand = 'Adidas') as net_rev_sl",
      'SQLResult': "Result of the SQL query",
      'Answer' : qns24},
     {'Question' : "If we sell all the tshirt in the inventory, what will be my total revenue,consider stock quantity as per piece price and sell all the tshirt irrrespective of that have and do not have discount",
      'SQLQuery' : "select (Select sum((price*stock_quantity)) from t_shirts as t left join discounts as d on t.t_shirt_id=d.t_shirt_id where d.t_shirt_id is null)+(select sum((t.price*t.stock_quantity)-((t.price*t.stock_quantity)*(d.pct_discount/100))) as net_sal from t_shirts as t inner join discounts as d on t.t_shirt_id=d.t_shirt_id) as overall_net_sales",
      'SQLResult': "Result of the SQL query",
      'Answer' : qns25
     }
]
